# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 23:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('soundcloud_connect', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song', models.FileField(upload_to='songs')),
                ('track_url', models.URLField()),
                ('profile_url', models.URLField()),
                ('follow_checkbox', models.BooleanField()),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='soundcloud_connect.Soundcloud_User')),
            ],
        ),
    ]
