# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-22 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soundcloud_User',
            fields=[
                ('permanent_link', models.CharField(default='not-present', max_length=200)),
                ('access_token', models.CharField(max_length=200)),
                ('soundcloud_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
    ]
